apiVersion: anzograph.clusters.cambridgesemantics.com/v2
kind: AnzoGraph
metadata:
  name: azg01
spec:
  db:
    nodeConfig:
      spec:
        replicas: 1
        selector:
          matchLabels:
            app_data: anzograph-data-grpc
            app_mgmt: anzograph-mgmt-grpc
        serviceName: anzograph-azg01
        template:
          metadata:
            labels:
              app_data: anzograph-data-grpc
              app_mgmt: anzograph-mgmt-grpc
          spec:
            containers:
            - image: registry.connect.redhat.com/cambridgesemantics/anzograph-db@sha256:97584695da2af0cf8b4af7a53808f587a787c84504518fe447997dbbf78fee69
              name: db
              resources:
                limits:
                  cpu: 8000m
                  memory: 8Gi
                requests:
                  cpu: 8000m
                  memory: 8Gi
            serviceAccountName: anzograph-operator
  deployFrontend: false
  frontend:
    nodeConfig:
      spec:
        replicas: 1
        selector:
          matchLabels:
            app_mgmt: anzograph-frontend
        serviceName: anzograph-azg01
        template:
          metadata:
            labels:
              app_mgmt: anzograph-frontend
          spec:
            containers:
            - image: registry.connect.redhat.com/cambridgesemantics/anzograph-frontend@sha256:7b4299fcbeffec21208f4e2d3032f24b08736f76bf7bffdfdb9e1777ba8949c9
              name: frontend
              resources:
                limits:
                  cpu: 2000m
                  memory: 4Gi
                requests:
                  cpu: 2000m
                  memory: 4Gi
            serviceAccountName: anzograph-operator
status: {}
